version: '3'

services:
  ziio_db:
    image: mysql:8.0.33
    container_name: ziio_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=ziio
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ziio_db_data:/var/lib/mysql
    networks:
      - app-network

  ziio_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ziio_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://ziio_db:3306/ziio?useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ziio_user
      SPRING_DATASOURCE_PASSWORD: ziio1234
    depends_on:
      - ziio_db
    networks:
      - app-network

networks:
  app-network:

volumes:
  ziio_db_data: